include $(APPDIR)/Make.defs

# Laboratorio 01 application

PROGNAME = lab01
PRIORITY = SCHED_PRIORITY_DEFAULT
STACKSIZE = 8192
MODULE = $(CONFIG_EXAMPLES_LAB01)

MAINSRC = lab01_main.c

include $(APPDIR)/Application.mk
